# Generated by Django 4.2.1 on 2023-05-07 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='field1',
            new_name='Italic',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field2',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
