# Generated by Django 4.2.1 on 2023-05-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_mymodel_signature_mymodel_underlinetxt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='underlinetxt',
            new_name='centertxt',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='Italic',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
