# Generated by Django 4.2.1 on 2023-05-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_rename_underlinetxt_mymodel_centertxt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='mymodel',
            old_name='Number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='Text',
        ),
    ]
