# Generated by Django 4.2.1 on 2023-05-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0008_mymodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
