# Generated by Django 4.2.1 on 2023-05-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0011_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
